const constants = {
  ADD_ITEM: 'ADD_ITEM',
  CLEAR_ITEM: 'CLEAR_ITEM',
  COMPLETE_ITEM: 'COMPLETE_ITEM',
  SET_VISIBLE: 'SET_VISIBLE',
  SET_INVISIBLE: 'SET_INVISIBLE',
  CHANGE_INPUT: 'CHANGE_INPUT',
  CLEAR_INPUT: 'CLEAR_INPUT'
}

export default constants